---
# tasks file for nomad
- name: apt key for hashicorp
  become: yes
  apt_key:
    url:  https://apt.releases.hashicorp.com/gpg

- name: add apt repo
  become: yes
  apt_repository:
    state: present
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    update_cache: yes

- name: install nomad binary
  become: yes
  apt:
    name: nomad
    state: latest
    autoclean: yes
    autoremove: yes

- name: try read nomad symetric encryption key
  local_action: set_fact nomad_symetric_key="{{ lookup ('file', 'files/nomad_secret') }}"
  ignore_errors: true
  run_once: true

- name: write nomad server config
  become: yes
  template:
    dest: /etc/nomad.d/nomad.hcl
    src: templates/nomad-server.hcl
  when: "'consul_server' in group_names"

- name: write nomad client config
  become: yes
  template:
    dest: /etc/nomad.d/nomad.hcl
    src: templates/nomad-client.hcl
  when: "'consul_client' in group_names"

- name: Add Logdir
  become: yes
  file:
    path: /var/log/nomad
    state: directory
    owner: nomad
    group: bin

- name: Add nomad to docker group
  become: yes
  user:
    name: nomad
    groups:
    - docker
    - nomad
  when: "'consul_client' in group_names"

- name: restart and enable nomad
  become: true
  service:
    name: nomad
    enabled: true
    state: restarted

- name: set GOSSIP Encryption Key
  shell:
    cmd: "nomad acl bootstrap"
  register: nomad_acl_bootstrap
  run_once: true
  when: "'consul_server' in group_names and nomad_symetric_key is not defined"

- name: save nomad token
  local_action: copy content="{{ nomad_acl_bootstrap['stdout_lines'] | select('match', '^Secret ID') | first | regex_replace('^Secret ID.*= (.*)', '\1') }}" dest=files/nomad_secret
  when: "'consul_server' in group_names and nomad_symetric_key is not defined"

- name: try read nomad symetric encryption key
  local_action: set_fact nomad_symetric_key="{{ lookup ('file', 'files/nomad_secret') }}"
  ignore_errors: true
  run_once: true
  when: nomad_symetric_key is not defined

- name: wait for nomad to come up
  shell:
    cmd: "NOMAD_TOKEN={{ nomad_symetric_key }} nomad server members"
  register: nomad_members_output
  retries: 120
  delay: 5
  until: nomad_members_output['rc'] == 0

- include: create_policies.yml
  run_once: true

- include: create_tokens.yml
  run_once: true







