---
# tasks file for dockerd
- name: install required package
  apt: name="{{ item }}" state=present
  loop:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - python-docker
    - python-pip

- name: add Docker's official GPG key
  apt_key: url="http://apt.dockerproject.org/gpg" state=present

- name: add Docker's repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo/ ubuntu-xenial main" update_cache=yes

- name: install latest Docker Engine
  apt: name="docker-ce"
