# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end


  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.

  config.vm.define "debian-jenkins" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-20.10"
    ubuntu.vm.network "private_network", ip: "192.168.33.12"

    ubuntu.trigger.after :up do |trigger|
      trigger.run = { path: "./postInstall.sh", args: "192.168.33.12"  }
    end

    ubuntu.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

    ubuntu.vm.provision "shell", inline: <<-SHELL
      sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo service sshd restart
      chmod 600 .ssh/authorized_keys
      chmod 700 .ssh
    SHELL
  end


end
