---
- name: configure git username
  git_config:
    name: user.name
    scope: global
    value: "{{ jenkins_user_name }}"
  become: true
  become_user: jenkins
  become_method: sudo

- name: configure git email
  git_config:
    name: user.email
    scope: global
    value: "{{ jenkins_user_email }}"
  become: true
  become_user: jenkins
  become_method: sudo

- name: configure git pull default
  git_config:
    name: pull.default
    scope: global
    value: machting
  become: true
  become_user: jenkins
  become_method: sudo

- name: determine jenkins home directory
  getent:
    database: passwd
    key: jenkins

- name: Create .ssh-dir
  file:
    path: /home/jenkins/.ssh
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0700

- name: Set gitlab to known hosts
  ansible.builtin.known_hosts:
    name: gitlab.bermuda.de
    key: gitlab.bermuda.de,144.76.95.221 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJAmHF3nvowXBjoQKQ5RzNH0FRFSGh/fdRR0lS88glFxzTz5reZz2Tjjnd372rGittzovWk4mIROu26FD6gpKhE=
    state: present
  become: true
  become_user: jenkins
  become_method: sudo
