- name: Create ssh dir
  file:
    dest: /home/jenkins/.ssh
    mode: 0700
    state: directory
    owner: jenkins
    group: jenkins

- name: Generate ssh-keypair in place
  community.crypto.openssh_keypair:
    path: /home/jenkins/.ssh/id_rsa

- name: Set Owner and Permission on ssh-keypair
  file:
    dest: "/home/jenkins/.ssh/{{ item }}"
    mode: 0600
    state: touch
    owner: jenkins
    group: jenkins
  loop:
    - id_rsa
    - id_rsa.pub


- name: retrieve ssh-pubkey
  ansible.builtin.slurp:
    src: /home/jenkins/.ssh/id_rsa.pub
  register: jenkins_pub_key

- name: Download terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip"
    dest: "/tmp/"

- name: Unpack terraform
  unarchive:
    dest: /usr/bin
    src: /tmp/terraform_0.14.5_linux_amd64.zip
    remote_src: yes
    mode: 0755

- name: create terraform-dir
  file:
    dest: "{{ jenkins_home }}/terraform"
    mode: 0755
    owner: jenkins
    state: directory

- name: install start script
  template:
    src: "jenkins/startAgent.sh.j2"
    dest: "{{ jenkins_home }}/terraform/startAgent.sh"
    mode: 0755

- name: install terraform script
  copy:
   src: "{{ jenkins_terraform_path }}"
   dest: "{{ jenkins_home }}"

- name: create terraform token file
  copy:
    dest: "{{ jenkins_home }}/terraform/token"
    content: "{{ jenkins_terraform_api_token }}"

- name: Create Jenkins SSH-Key on Terraform Host.
  terraform:
    project_path: "{{ jenkins_home }}/tf_create_ssh_pkey"
    state: present
    force_init: true
    variables:
      hcloud_token: "{{ jenkins_terraform_api_token }}"
      jenkins_ssh_pkey: "{{ jenkins_pub_key['content'] | b64decode }}"
      jenkins_key_name: "jenkins@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

